flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
    static: false
packages:
- '.'
extra-deps:
- git: https://github.com/jgm/citeproc
  commit: ee5cd1726037c79f6519d5be4822a1f795d09cad
- pandoc-types-1.22
- rfc5051-0.2
- texmath-0.12.0.2
- haddock-library-1.9.0
- skylighting-0.10.0.2
- skylighting-core-0.10.0.2
- doclayout-0.3
- emojis-0.1
- hslua-1.1.2
- jira-wiki-markup-1.3.2
- HsYAML-0.2.1.0
- HsYAML-aeson-0.2.0.0
- doctemplates-0.8.2
- commonmark-0.1.0.2
- commonmark-extensions-0.2.0.1
- commonmark-pandoc-0.2.0.0

ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-14.6
nix:
  packages: [zlib]

